'use client';

import { useMemo, useState } from 'react';
import { Chart } from '@/components/ui/chart';
import { PlotlyChart } from '@/components/charts/plotly-chart';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type ProjectChartsProps = {
  slug: string;
};

const babynamesBirthsRecent = [
  { name: '2015', value: 3700912 },
  { name: '2016', value: 3668698 },
  { name: '2017', value: 3576195 },
  { name: '2018', value: 3515897 },
  { name: '2019', value: 3470933 },
  { name: '2020', value: 3340577 },
  { name: '2021', value: 3387949 },
  { name: '2022', value: 3383135 },
  { name: '2023', value: 3311196 },
  { name: '2024', value: 3328501 },
];

const babynamesTopNames = [
  { name: 'James', value: 5262396 },
  { name: 'John', value: 5196210 },
  { name: 'Robert', value: 4866007 },
  { name: 'Michael', value: 4440391 },
  { name: 'William', value: 4205026 },
  { name: 'Mary', value: 4154332 },
  { name: 'David', value: 3682683 },
  { name: 'Joseph', value: 2672746 },
  { name: 'Richard', value: 2585535 },
  { name: 'Charles', value: 2441151 },
];

const babynamesUniqueNamesRecent = [
  { name: '2015', value: 30662 },
  { name: '2016', value: 30475 },
  { name: '2017', value: 30101 },
  { name: '2018', value: 29693 },
  { name: '2019', value: 29512 },
  { name: '2020', value: 28864 },
  { name: '2021', value: 28991 },
  { name: '2022', value: 29303 },
  { name: '2023', value: 29054 },
  { name: '2024', value: 29225 },
];

const babynamesUnisexNames = {
  names: ['Jessie', 'Riley', 'Casey', 'Jackie', 'Johnnie', 'Peyton', 'Dakota', 'Jaime'],
  female: [169704, 137477, 77869, 91167, 49154, 86635, 40410, 50031],
  male: [111202, 103344, 115589, 78836, 102028, 51982, 92020, 71068],
};

const f5BreachReturns = {
  dates: ['2025-10-16', '2025-10-17', '2025-10-20', '2025-10-21', '2025-10-22', '2025-10-23'],
  returns: [-0.107029, 0.018791, -0.014623, 0.00914, -0.004579, 0.013497],
};

const f5BreachCumulativeIndex = f5BreachReturns.returns.reduce<number[]>((acc, value, idx) => {
  const base = idx === 0 ? 100 : acc[idx - 1];
  acc.push(Number((base * (1 + value)).toFixed(2)));
  return acc;
}, []);

const f5BreachDiD = [
  { name: 'Breach Effect (DiD)', value: -0.0951 },
  { name: 'Placebo Effect', value: 0.0042 },
];

const f5BreachCoefficients = [
  { name: 'Intercept', value: 0.0027 },
  { name: 'Treated', value: -0.0003 },
  { name: 'Post', value: -0.0143 },
  { name: 'Treated × Post', value: -0.0951 },
];

const ssaApprovalTopStates = [
  { name: 'KS', value: 60.57 },
  { name: 'AK', value: 56.53 },
  { name: 'NH', value: 50.57 },
  { name: 'NE', value: 47.21 },
  { name: 'RI', value: 46.14 },
  { name: 'ND', value: 45.52 },
  { name: 'WY', value: 44.22 },
  { name: 'VA', value: 44.12 },
];

const ssaApprovalBottomStates = [
  { name: 'TX', value: 33.71 },
  { name: 'NC', value: 33.07 },
  { name: 'AL', value: 32.87 },
  { name: 'KY', value: 31.63 },
  { name: 'AZ', value: 31.43 },
  { name: 'IN', value: 31.37 },
  { name: 'WV', value: 30.71 },
  { name: 'MS', value: 30.64 },
  { name: 'OK', value: 29.14 },
  { name: 'DC', value: 26.88 },
];

const ssaAdultChildRates = {
  states: ['KS', 'AK', 'NH', 'NE', 'RI'],
  adult: [58.55, 53.1, 49.69, 44.64, 44.87],
  child: [64.1, 83.43, 66.01, 67.74, 56.69],
};

const ssaApprovalByYear: Record<number, { state: string; rate: number }[]> = {
  2001: [
    { state: 'AK', rate: 49.19 },
    { state: 'AL', rate: 39.32 },
    { state: 'AR', rate: 32.63 },
    { state: 'AZ', rate: 52.45 },
    { state: 'CA', rate: 45.39 },
    { state: 'CO', rate: 39.46 },
    { state: 'CT', rate: 44.71 },
    { state: 'DC', rate: 51.81 },
    { state: 'DE', rate: 53.02 },
    { state: 'FL', rate: 38.73 },
    { state: 'GA', rate: 32.73 },
    { state: 'HI', rate: 53.32 },
    { state: 'IA', rate: 42.51 },
    { state: 'ID', rate: 40.99 },
    { state: 'IL', rate: 40.1 },
    { state: 'IN', rate: 35.46 },
    { state: 'KS', rate: 34.75 },
    { state: 'KY', rate: 32.45 },
    { state: 'LA', rate: 34.22 },
    { state: 'MA', rate: 45.39 },
    { state: 'MD', rate: 39.79 },
    { state: 'ME', rate: 42.28 },
    { state: 'MI', rate: 40.42 },
    { state: 'MN', rate: 50.6 },
    { state: 'MO', rate: 38.82 },
    { state: 'MS', rate: 30.04 },
    { state: 'MT', rate: 34.18 },
    { state: 'NC', rate: 34.64 },
    { state: 'ND', rate: 36.27 },
    { state: 'NE', rate: 36.82 },
    { state: 'NH', rate: 65.55 },
    { state: 'NJ', rate: 47.58 },
    { state: 'NM', rate: 40.78 },
    { state: 'NV', rate: 56.95 },
    { state: 'NY', rate: 42.9 },
    { state: 'OH', rate: 34.21 },
    { state: 'OK', rate: 35.48 },
    { state: 'OR', rate: 40.25 },
    { state: 'PA', rate: 50.8 },
    { state: 'PR', rate: 34.59 },
    { state: 'RI', rate: 48.31 },
    { state: 'SC', rate: 35.57 },
    { state: 'SD', rate: 36.44 },
    { state: 'TN', rate: 27.44 },
    { state: 'TX', rate: 37.36 },
    { state: 'UT', rate: 37.74 },
    { state: 'VA', rate: 40.87 },
    { state: 'VT', rate: 48.37 },
    { state: 'WA', rate: 43.2 },
    { state: 'WI', rate: 41.04 },
    { state: 'WV', rate: 32.35 },
    { state: 'WY', rate: 32.64 },
  ],
  2002: [
    { state: 'AK', rate: 41.57 },
    { state: 'AL', rate: 32.16 },
    { state: 'AR', rate: 35.41 },
    { state: 'AZ', rate: 48.4 },
    { state: 'CA', rate: 45.56 },
    { state: 'CO', rate: 29.96 },
    { state: 'CT', rate: 42.14 },
    { state: 'DC', rate: 50.93 },
    { state: 'DE', rate: 48.27 },
    { state: 'FL', rate: 38.12 },
    { state: 'GA', rate: 29.98 },
    { state: 'HI', rate: 53.6 },
    { state: 'IA', rate: 39.34 },
    { state: 'ID', rate: 44.23 },
    { state: 'IL', rate: 40.93 },
    { state: 'IN', rate: 33.04 },
    { state: 'KS', rate: 32.37 },
    { state: 'KY', rate: 31.61 },
    { state: 'LA', rate: 32.27 },
    { state: 'MA', rate: 45.18 },
    { state: 'MD', rate: 37.6 },
    { state: 'ME', rate: 42.37 },
    { state: 'MI', rate: 40.7 },
    { state: 'MN', rate: 46.48 },
    { state: 'MO', rate: 35.06 },
    { state: 'MS', rate: 29.25 },
    { state: 'MT', rate: 30.79 },
    { state: 'NC', rate: 32.89 },
    { state: 'ND', rate: 35.07 },
    { state: 'NE', rate: 35.02 },
    { state: 'NH', rate: 59.26 },
    { state: 'NJ', rate: 47.64 },
    { state: 'NM', rate: 42.59 },
    { state: 'NV', rate: 52.21 },
    { state: 'NY', rate: 39.03 },
    { state: 'OH', rate: 30.48 },
    { state: 'OK', rate: 36.08 },
    { state: 'OR', rate: 37.23 },
    { state: 'PA', rate: 46.87 },
    { state: 'PR', rate: 32.71 },
    { state: 'RI', rate: 45.33 },
    { state: 'SC', rate: 33.32 },
    { state: 'SD', rate: 35.91 },
    { state: 'TN', rate: 26.63 },
    { state: 'TX', rate: 39.85 },
    { state: 'UT', rate: 34.84 },
    { state: 'VA', rate: 41.92 },
    { state: 'VT', rate: 50.05 },
    { state: 'WA', rate: 41.08 },
    { state: 'WI', rate: 38.98 },
    { state: 'WV', rate: 33.5 },
    { state: 'WY', rate: 31.47 },
  ],
  2003: [
    { state: 'AK', rate: 43.26 },
    { state: 'AL', rate: 29.58 },
    { state: 'AR', rate: 36.91 },
    { state: 'AZ', rate: 46.75 },
    { state: 'CA', rate: 44.66 },
    { state: 'CO', rate: 26.46 },
    { state: 'CT', rate: 37.95 },
    { state: 'DC', rate: 49.36 },
    { state: 'DE', rate: 48.94 },
    { state: 'FL', rate: 35.32 },
    { state: 'GA', rate: 28.35 },
    { state: 'HI', rate: 52.39 },
    { state: 'IA', rate: 35.84 },
    { state: 'ID', rate: 39.85 },
    { state: 'IL', rate: 39.05 },
    { state: 'IN', rate: 32.36 },
    { state: 'KS', rate: 32.84 },
    { state: 'KY', rate: 32.55 },
    { state: 'LA', rate: 31.28 },
    { state: 'MA', rate: 45.57 },
    { state: 'MD', rate: 34.07 },
    { state: 'ME', rate: 42.29 },
    { state: 'MI', rate: 36.11 },
    { state: 'MN', rate: 42.48 },
    { state: 'MO', rate: 33.34 },
    { state: 'MS', rate: 27.42 },
    { state: 'MT', rate: 30.47 },
    { state: 'NC', rate: 33.01 },
    { state: 'ND', rate: 30.59 },
    { state: 'NE', rate: 34.87 },
    { state: 'NH', rate: 56.99 },
    { state: 'NJ', rate: 50.35 },
    { state: 'NM', rate: 40.45 },
    { state: 'NV', rate: 49.73 },
    { state: 'NY', rate: 38.41 },
    { state: 'OH', rate: 29.06 },
    { state: 'OK', rate: 33.91 },
    { state: 'OR', rate: 33.84 },
    { state: 'PA', rate: 45.09 },
    { state: 'PR', rate: 29.55 },
    { state: 'RI', rate: 45.06 },
    { state: 'SC', rate: 30.61 },
    { state: 'SD', rate: 30.62 },
    { state: 'TN', rate: 25.84 },
    { state: 'TX', rate: 38.67 },
    { state: 'UT', rate: 30.52 },
    { state: 'VA', rate: 38.48 },
    { state: 'VT', rate: 42.77 },
    { state: 'WA', rate: 41.4 },
    { state: 'WI', rate: 37.5 },
    { state: 'WV', rate: 30.27 },
    { state: 'WY', rate: 31.15 },
  ],
  2004: [
    { state: 'AK', rate: 38.89 },
    { state: 'AL', rate: 28.33 },
    { state: 'AR', rate: 37.77 },
    { state: 'AZ', rate: 46.92 },
    { state: 'CA', rate: 46.45 },
    { state: 'CO', rate: 29.05 },
    { state: 'CT', rate: 36.74 },
    { state: 'DC', rate: 49.69 },
    { state: 'DE', rate: 51.55 },
    { state: 'FL', rate: 33.27 },
    { state: 'GA', rate: 26.68 },
    { state: 'HI', rate: 52.31 },
    { state: 'IA', rate: 33.89 },
    { state: 'ID', rate: 41.26 },
    { state: 'IL', rate: 37.36 },
    { state: 'IN', rate: 30.87 },
    { state: 'KS', rate: 31.77 },
    { state: 'KY', rate: 32.6 },
    { state: 'LA', rate: 33.69 },
    { state: 'MA', rate: 45.32 },
    { state: 'MD', rate: 33.64 },
    { state: 'ME', rate: 39.1 },
    { state: 'MI', rate: 34.8 },
    { state: 'MN', rate: 41.62 },
    { state: 'MO', rate: 31.83 },
    { state: 'MS', rate: 26.65 },
    { state: 'MT', rate: 32.94 },
    { state: 'NC', rate: 32.25 },
    { state: 'ND', rate: 30.65 },
    { state: 'NE', rate: 32.66 },
    { state: 'NH', rate: 60.13 },
    { state: 'NJ', rate: 52.23 },
    { state: 'NM', rate: 40.9 },
    { state: 'NV', rate: 46.32 },
    { state: 'NY', rate: 42 },
    { state: 'OH', rate: 29.45 },
    { state: 'OK', rate: 34.7 },
    { state: 'OR', rate: 33.09 },
    { state: 'PA', rate: 42.7 },
    { state: 'PR', rate: 31.41 },
    { state: 'RI', rate: 49.82 },
    { state: 'SC', rate: 29.43 },
    { state: 'SD', rate: 31.89 },
    { state: 'TN', rate: 25.53 },
    { state: 'TX', rate: 36.93 },
    { state: 'UT', rate: 31.35 },
    { state: 'VA', rate: 42.85 },
    { state: 'VT', rate: 45.47 },
    { state: 'WA', rate: 39.43 },
    { state: 'WI', rate: 36.6 },
    { state: 'WV', rate: 31.26 },
    { state: 'WY', rate: 37.13 },
  ],
  2005: [
    { state: 'AK', rate: 42.14 },
    { state: 'AL', rate: 28.45 },
    { state: 'AR', rate: 35.17 },
    { state: 'AZ', rate: 43.18 },
    { state: 'CA', rate: 43.82 },
    { state: 'CO', rate: 28.42 },
    { state: 'CT', rate: 37.88 },
    { state: 'DC', rate: 45.97 },
    { state: 'DE', rate: 47.46 },
    { state: 'FL', rate: 33.77 },
    { state: 'GA', rate: 26.04 },
    { state: 'HI', rate: 52.84 },
    { state: 'IA', rate: 33.21 },
    { state: 'ID', rate: 40.2 },
    { state: 'IL', rate: 33.04 },
    { state: 'IN', rate: 31.38 },
    { state: 'KS', rate: 29.7 },
    { state: 'KY', rate: 30.69 },
    { state: 'LA', rate: 34.86 },
    { state: 'MA', rate: 46.13 },
    { state: 'MD', rate: 35.25 },
    { state: 'ME', rate: 38.74 },
    { state: 'MI', rate: 31.18 },
    { state: 'MN', rate: 40.61 },
    { state: 'MO', rate: 28.91 },
    { state: 'MS', rate: 26.77 },
    { state: 'MT', rate: 33.24 },
    { state: 'NC', rate: 31.34 },
    { state: 'ND', rate: 32.09 },
    { state: 'NE', rate: 32.13 },
    { state: 'NH', rate: 60.5 },
    { state: 'NJ', rate: 49.03 },
    { state: 'NM', rate: 43.48 },
    { state: 'NV', rate: 45.77 },
    { state: 'NY', rate: 41.86 },
    { state: 'OH', rate: 28.52 },
    { state: 'OK', rate: 35.36 },
    { state: 'OR', rate: 30.59 },
    { state: 'PA', rate: 41.2 },
    { state: 'PR', rate: 34.04 },
    { state: 'RI', rate: 46.59 },
    { state: 'SC', rate: 27.46 },
    { state: 'SD', rate: 34.26 },
    { state: 'TN', rate: 23.18 },
    { state: 'TX', rate: 39.22 },
    { state: 'UT', rate: 28.68 },
    { state: 'VA', rate: 46.08 },
    { state: 'VT', rate: 44.94 },
    { state: 'WA', rate: 39.06 },
    { state: 'WI', rate: 33.4 },
    { state: 'WV', rate: 31.39 },
    { state: 'WY', rate: 43.62 },
  ],
  2006: [
    { state: 'AK', rate: 43.1 },
    { state: 'AL', rate: 28.42 },
    { state: 'AR', rate: 32.36 },
    { state: 'AZ', rate: 40.45 },
    { state: 'CA', rate: 43.82 },
    { state: 'CO', rate: 30.74 },
    { state: 'CT', rate: 37.16 },
    { state: 'DC', rate: 53.59 },
    { state: 'DE', rate: 48.01 },
    { state: 'FL', rate: 34.03 },
    { state: 'GA', rate: 25.27 },
    { state: 'HI', rate: 53.49 },
    { state: 'IA', rate: 31.35 },
    { state: 'ID', rate: 38.33 },
    { state: 'IL', rate: 33.36 },
    { state: 'IN', rate: 31.18 },
    { state: 'KS', rate: 28.31 },
    { state: 'KY', rate: 30.38 },
    { state: 'LA', rate: 36.2 },
    { state: 'MA', rate: 45.67 },
    { state: 'MD', rate: 34.07 },
    { state: 'ME', rate: 37.82 },
    { state: 'MI', rate: 29.24 },
    { state: 'MN', rate: 40.69 },
    { state: 'MO', rate: 30.05 },
    { state: 'MS', rate: 25.4 },
    { state: 'MT', rate: 36.79 },
    { state: 'NC', rate: 30.03 },
    { state: 'ND', rate: 38.86 },
    { state: 'NE', rate: 32.88 },
    { state: 'NH', rate: 58.95 },
    { state: 'NJ', rate: 46.89 },
    { state: 'NM', rate: 40.77 },
    { state: 'NV', rate: 48.84 },
    { state: 'NY', rate: 43.21 },
    { state: 'OH', rate: 26.79 },
    { state: 'OK', rate: 36.68 },
    { state: 'OR', rate: 29.96 },
    { state: 'PA', rate: 41.02 },
    { state: 'PR', rate: 36.14 },
    { state: 'RI', rate: 42.93 },
    { state: 'SC', rate: 23.51 },
    { state: 'SD', rate: 33.49 },
    { state: 'TN', rate: 22.98 },
    { state: 'TX', rate: 39.14 },
    { state: 'UT', rate: 35.53 },
    { state: 'VA', rate: 44.73 },
    { state: 'VT', rate: 49.45 },
    { state: 'WA', rate: 38.77 },
    { state: 'WI', rate: 33.65 },
    { state: 'WV', rate: 29.64 },
    { state: 'WY', rate: 41.38 },
  ],
  2007: [
    { state: 'AK', rate: 42.15 },
    { state: 'AL', rate: 27.78 },
    { state: 'AR', rate: 34.5 },
    { state: 'AZ', rate: 38.25 },
    { state: 'CA', rate: 41.24 },
    { state: 'CO', rate: 33.99 },
    { state: 'CT', rate: 35.49 },
    { state: 'DC', rate: 47.63 },
    { state: 'DE', rate: 45.67 },
    { state: 'FL', rate: 33.23 },
    { state: 'GA', rate: 25.04 },
    { state: 'HI', rate: 49.49 },
    { state: 'IA', rate: 30.93 },
    { state: 'ID', rate: 36.82 },
    { state: 'IL', rate: 32.99 },
    { state: 'IN', rate: 32.89 },
    { state: 'KS', rate: 28.12 },
    { state: 'KY', rate: 29.43 },
    { state: 'LA', rate: 33.3 },
    { state: 'MA', rate: 46.32 },
    { state: 'MD', rate: 33.37 },
    { state: 'ME', rate: 36.6 },
    { state: 'MI', rate: 27.9 },
    { state: 'MN', rate: 37.97 },
    { state: 'MO', rate: 32.76 },
    { state: 'MS', rate: 23.77 },
    { state: 'MT', rate: 38.13 },
    { state: 'NC', rate: 29.34 },
    { state: 'ND', rate: 37.49 },
    { state: 'NE', rate: 31.29 },
    { state: 'NH', rate: 55.59 },
    { state: 'NJ', rate: 45.17 },
    { state: 'NM', rate: 36.09 },
    { state: 'NV', rate: 46.21 },
    { state: 'NY', rate: 41.85 },
    { state: 'OH', rate: 26.12 },
    { state: 'OK', rate: 38.23 },
    { state: 'OR', rate: 32.15 },
    { state: 'PA', rate: 37.57 },
    { state: 'PR', rate: 40.7 },
    { state: 'RI', rate: 39.94 },
    { state: 'SC', rate: 24.46 },
    { state: 'SD', rate: 34.56 },
    { state: 'TN', rate: 23.52 },
    { state: 'TX', rate: 42.1 },
    { state: 'UT', rate: 39.1 },
    { state: 'VA', rate: 40.17 },
    { state: 'VT', rate: 51.05 },
    { state: 'WA', rate: 38.58 },
    { state: 'WI', rate: 34.19 },
    { state: 'WV', rate: 27.07 },
    { state: 'WY', rate: 44.6 },
  ],
  2008: [
    { state: 'AK', rate: 42.98 },
    { state: 'AL', rate: 31.89 },
    { state: 'AR', rate: 36.18 },
    { state: 'AZ', rate: 37.17 },
    { state: 'CA', rate: 39.3 },
    { state: 'CO', rate: 35.03 },
    { state: 'CT', rate: 33.37 },
    { state: 'DC', rate: 44.91 },
    { state: 'DE', rate: 44.92 },
    { state: 'FL', rate: 33.83 },
    { state: 'GA', rate: 25.08 },
    { state: 'HI', rate: 52.83 },
    { state: 'IA', rate: 32.63 },
    { state: 'ID', rate: 39.24 },
    { state: 'IL', rate: 35.79 },
    { state: 'IN', rate: 36.47 },
    { state: 'KS', rate: 36.2 },
    { state: 'KY', rate: 28.93 },
    { state: 'LA', rate: 36.72 },
    { state: 'MA', rate: 46.1 },
    { state: 'MD', rate: 37.88 },
    { state: 'ME', rate: 35.88 },
    { state: 'MI', rate: 30.47 },
    { state: 'MN', rate: 37.78 },
    { state: 'MO', rate: 33.85 },
    { state: 'MS', rate: 24.62 },
    { state: 'MT', rate: 41.68 },
    { state: 'NC', rate: 30.96 },
    { state: 'ND', rate: 38.34 },
    { state: 'NE', rate: 37.59 },
    { state: 'NH', rate: 52.22 },
    { state: 'NJ', rate: 45.19 },
    { state: 'NM', rate: 36.57 },
    { state: 'NV', rate: 43 },
    { state: 'NY', rate: 44.52 },
    { state: 'OH', rate: 27.3 },
    { state: 'OK', rate: 39.86 },
    { state: 'OR', rate: 37.42 },
    { state: 'PA', rate: 36.96 },
    { state: 'PR', rate: 43.73 },
    { state: 'RI', rate: 38.28 },
    { state: 'SC', rate: 31.2 },
    { state: 'SD', rate: 35.9 },
    { state: 'TN', rate: 25.21 },
    { state: 'TX', rate: 42.7 },
    { state: 'UT', rate: 44.41 },
    { state: 'VA', rate: 39.78 },
    { state: 'VT', rate: 48.08 },
    { state: 'WA', rate: 39.93 },
    { state: 'WI', rate: 40.45 },
    { state: 'WV', rate: 26.69 },
    { state: 'WY', rate: 47.67 },
  ],
  2009: [
    { state: 'AK', rate: 51.23 },
    { state: 'AL', rate: 31.63 },
    { state: 'AR', rate: 37.14 },
    { state: 'AZ', rate: 34.34 },
    { state: 'CA', rate: 37.6 },
    { state: 'CO', rate: 39.36 },
    { state: 'CT', rate: 31.93 },
    { state: 'DC', rate: 40.48 },
    { state: 'DE', rate: 42.88 },
    { state: 'FL', rate: 34.75 },
    { state: 'GA', rate: 28.71 },
    { state: 'HI', rate: 50.27 },
    { state: 'IA', rate: 33.33 },
    { state: 'ID', rate: 38.61 },
    { state: 'IL', rate: 36 },
    { state: 'IN', rate: 35.06 },
    { state: 'KS', rate: 38.29 },
    { state: 'KY', rate: 32.33 },
    { state: 'LA', rate: 36.25 },
    { state: 'MA', rate: 46.24 },
    { state: 'MD', rate: 38.67 },
    { state: 'ME', rate: 32.41 },
    { state: 'MI', rate: 36.56 },
    { state: 'MN', rate: 39.64 },
    { state: 'MO', rate: 33.58 },
    { state: 'MS', rate: 26.56 },
    { state: 'MT', rate: 41.53 },
    { state: 'NC', rate: 29.59 },
    { state: 'ND', rate: 40.41 },
    { state: 'NE', rate: 38.63 },
    { state: 'NH', rate: 51.93 },
    { state: 'NJ', rate: 48.41 },
    { state: 'NM', rate: 37.19 },
    { state: 'NV', rate: 41.44 },
    { state: 'NY', rate: 45.01 },
    { state: 'OH', rate: 28.61 },
    { state: 'OK', rate: 38.56 },
    { state: 'OR', rate: 39.87 },
    { state: 'PA', rate: 35.31 },
    { state: 'PR', rate: 59.77 },
    { state: 'RI', rate: 37.54 },
    { state: 'SC', rate: 31.9 },
    { state: 'SD', rate: 40.02 },
    { state: 'TN', rate: 27.53 },
    { state: 'TX', rate: 43.5 },
    { state: 'UT', rate: 44.38 },
    { state: 'VA', rate: 40.36 },
    { state: 'VT', rate: 48.33 },
    { state: 'WA', rate: 39.92 },
    { state: 'WI', rate: 44.08 },
    { state: 'WV', rate: 26.43 },
    { state: 'WY', rate: 51.75 },
  ],
  2010: [
    { state: 'AK', rate: 48.94 },
    { state: 'AL', rate: 30.78 },
    { state: 'AR', rate: 33.44 },
    { state: 'AZ', rate: 31.4 },
    { state: 'CA', rate: 36.45 },
    { state: 'CO', rate: 38.12 },
    { state: 'CT', rate: 33.4 },
    { state: 'DC', rate: 47.88 },
    { state: 'DE', rate: 40.35 },
    { state: 'FL', rate: 32.67 },
    { state: 'GA', rate: 28.74 },
    { state: 'HI', rate: 47.62 },
    { state: 'IA', rate: 32.58 },
    { state: 'ID', rate: 34.1 },
    { state: 'IL', rate: 33.77 },
    { state: 'IN', rate: 33.31 },
    { state: 'KS', rate: 36.91 },
    { state: 'KY', rate: 30.01 },
    { state: 'LA', rate: 35.22 },
    { state: 'MA', rate: 43.69 },
    { state: 'MD', rate: 37.37 },
    { state: 'ME', rate: 31.78 },
    { state: 'MI', rate: 34.32 },
    { state: 'MN', rate: 36.45 },
    { state: 'MO', rate: 32.66 },
    { state: 'MS', rate: 24.9 },
    { state: 'MT', rate: 39.02 },
    { state: 'NC', rate: 28.08 },
    { state: 'ND', rate: 43.24 },
    { state: 'NE', rate: 39.4 },
    { state: 'NH', rate: 49.5 },
    { state: 'NJ', rate: 46.51 },
    { state: 'NM', rate: 35.22 },
    { state: 'NV', rate: 38.29 },
    { state: 'NY', rate: 41.58 },
    { state: 'OH', rate: 31.3 },
    { state: 'OK', rate: 35.82 },
    { state: 'OR', rate: 38.53 },
    { state: 'PA', rate: 34.38 },
    { state: 'PR', rate: 63.44 },
    { state: 'RI', rate: 34.71 },
    { state: 'SC', rate: 30.27 },
    { state: 'SD', rate: 41.34 },
    { state: 'TN', rate: 25.75 },
    { state: 'TX', rate: 41.7 },
    { state: 'UT', rate: 40.66 },
    { state: 'VA', rate: 38.78 },
    { state: 'VT', rate: 43.59 },
    { state: 'WA', rate: 40.36 },
    { state: 'WI', rate: 38.3 },
    { state: 'WV', rate: 26.19 },
    { state: 'WY', rate: 49.52 },
  ],
  2011: [
    { state: 'AK', rate: 47.23 },
    { state: 'AL', rate: 29.66 },
    { state: 'AR', rate: 33.46 },
    { state: 'AZ', rate: 30.02 },
    { state: 'CA', rate: 34.95 },
    { state: 'CO', rate: 35.68 },
    { state: 'CT', rate: 31.26 },
    { state: 'DC', rate: 41.37 },
    { state: 'DE', rate: 34.44 },
    { state: 'FL', rate: 30.25 },
    { state: 'GA', rate: 27.23 },
    { state: 'HI', rate: 40.55 },
    { state: 'IA', rate: 32.37 },
    { state: 'ID', rate: 33.1 },
    { state: 'IL', rate: 31.47 },
    { state: 'IN', rate: 31.25 },
    { state: 'KS', rate: 38.47 },
    { state: 'KY', rate: 27.17 },
    { state: 'LA', rate: 34.08 },
    { state: 'MA', rate: 42.6 },
    { state: 'MD', rate: 33.26 },
    { state: 'ME', rate: 32.68 },
    { state: 'MI', rate: 32.44 },
    { state: 'MN', rate: 34.34 },
    { state: 'MO', rate: 33.48 },
    { state: 'MS', rate: 24.94 },
    { state: 'MT', rate: 38.98 },
    { state: 'NC', rate: 25.87 },
    { state: 'ND', rate: 42.28 },
    { state: 'NE', rate: 36.85 },
    { state: 'NH', rate: 49.02 },
    { state: 'NJ', rate: 45.54 },
    { state: 'NM', rate: 31.39 },
    { state: 'NV', rate: 36.58 },
    { state: 'NY', rate: 40.34 },
    { state: 'OH', rate: 30.49 },
    { state: 'OK', rate: 30.7 },
    { state: 'OR', rate: 35.96 },
    { state: 'PA', rate: 33.83 },
    { state: 'PR', rate: 66.07 },
    { state: 'RI', rate: 33.49 },
    { state: 'SC', rate: 28.18 },
    { state: 'SD', rate: 40.66 },
    { state: 'TN', rate: 24.76 },
    { state: 'TX', rate: 38.42 },
    { state: 'UT', rate: 40.65 },
    { state: 'VA', rate: 35.23 },
    { state: 'VT', rate: 41.2 },
    { state: 'WA', rate: 38.58 },
    { state: 'WI', rate: 35.05 },
    { state: 'WV', rate: 27.05 },
    { state: 'WY', rate: 51.71 },
  ],
  2012: [
    { state: 'AK', rate: 47.5 },
    { state: 'AL', rate: 30.78 },
    { state: 'AR', rate: 31.6 },
    { state: 'AZ', rate: 31.77 },
    { state: 'CA', rate: 34.08 },
    { state: 'CO', rate: 33.78 },
    { state: 'CT', rate: 30.97 },
    { state: 'DC', rate: 37.96 },
    { state: 'DE', rate: 34.22 },
    { state: 'FL', rate: 29.86 },
    { state: 'GA', rate: 26.94 },
    { state: 'HI', rate: 35.39 },
    { state: 'IA', rate: 36.24 },
    { state: 'ID', rate: 35.95 },
    { state: 'IL', rate: 31.1 },
    { state: 'IN', rate: 30.26 },
    { state: 'KS', rate: 36.57 },
    { state: 'KY', rate: 26.99 },
    { state: 'LA', rate: 31.61 },
    { state: 'MA', rate: 40.16 },
    { state: 'MD', rate: 29.78 },
    { state: 'ME', rate: 31.27 },
    { state: 'MI', rate: 30.69 },
    { state: 'MN', rate: 35.35 },
    { state: 'MO', rate: 33.15 },
    { state: 'MS', rate: 24.57 },
    { state: 'MT', rate: 36.94 },
    { state: 'NC', rate: 27.35 },
    { state: 'ND', rate: 42.61 },
    { state: 'NE', rate: 36.47 },
    { state: 'NH', rate: 49.19 },
    { state: 'NJ', rate: 42.17 },
    { state: 'NM', rate: 38.47 },
    { state: 'NV', rate: 35.16 },
    { state: 'NY', rate: 39.61 },
    { state: 'OH', rate: 30.85 },
    { state: 'OK', rate: 31.15 },
    { state: 'OR', rate: 34.67 },
    { state: 'PA', rate: 34.55 },
    { state: 'PR', rate: 59.1 },
    { state: 'RI', rate: 33.91 },
    { state: 'SC', rate: 27.15 },
    { state: 'SD', rate: 41.96 },
    { state: 'TN', rate: 25.69 },
    { state: 'TX', rate: 34.34 },
    { state: 'UT', rate: 38.88 },
    { state: 'VA', rate: 36.6 },
    { state: 'VT', rate: 41.85 },
    { state: 'WA', rate: 37.58 },
    { state: 'WI', rate: 37.09 },
    { state: 'WV', rate: 26.62 },
    { state: 'WY', rate: 54.74 },
  ],
  2013: [
    { state: 'AK', rate: 46.85 },
    { state: 'AL', rate: 28.35 },
    { state: 'AR', rate: 31.28 },
    { state: 'AZ', rate: 30.53 },
    { state: 'CA', rate: 34.15 },
    { state: 'CO', rate: 34.19 },
    { state: 'CT', rate: 30.09 },
    { state: 'DC', rate: 37.17 },
    { state: 'DE', rate: 32.7 },
    { state: 'FL', rate: 30.81 },
    { state: 'GA', rate: 25.62 },
    { state: 'HI', rate: 34.44 },
    { state: 'IA', rate: 37.89 },
    { state: 'ID', rate: 35.41 },
    { state: 'IL', rate: 32.09 },
    { state: 'IN', rate: 29.93 },
    { state: 'KS', rate: 38.6 },
    { state: 'KY', rate: 26.23 },
    { state: 'LA', rate: 33.72 },
    { state: 'MA', rate: 40.95 },
    { state: 'MD', rate: 30.37 },
    { state: 'ME', rate: 32.52 },
    { state: 'MI', rate: 30.85 },
    { state: 'MN', rate: 35.27 },
    { state: 'MO', rate: 33.55 },
    { state: 'MS', rate: 24.82 },
    { state: 'MT', rate: 37.32 },
    { state: 'NC', rate: 28.8 },
    { state: 'ND', rate: 42.9 },
    { state: 'NE', rate: 38.63 },
    { state: 'NH', rate: 49.79 },
    { state: 'NJ', rate: 40.27 },
    { state: 'NM', rate: 39.13 },
    { state: 'NV', rate: 39.37 },
    { state: 'NY', rate: 38.45 },
    { state: 'OH', rate: 32.23 },
    { state: 'OK', rate: 33.3 },
    { state: 'OR', rate: 35.34 },
    { state: 'PA', rate: 35.07 },
    { state: 'PR', rate: 51.13 },
    { state: 'RI', rate: 32.41 },
    { state: 'SC', rate: 30.22 },
    { state: 'SD', rate: 41.78 },
    { state: 'TN', rate: 25.56 },
    { state: 'TX', rate: 33.77 },
    { state: 'UT', rate: 36.39 },
    { state: 'VA', rate: 38.22 },
    { state: 'VT', rate: 41.37 },
    { state: 'WA', rate: 37.6 },
    { state: 'WI', rate: 36.95 },
    { state: 'WV', rate: 27.08 },
    { state: 'WY', rate: 54.52 },
  ],
  2014: [
    { state: 'AK', rate: 46.5 },
    { state: 'AL', rate: 27.83 },
    { state: 'AR', rate: 31.23 },
    { state: 'AZ', rate: 28.32 },
    { state: 'CA', rate: 32.87 },
    { state: 'CO', rate: 31.58 },
    { state: 'CT', rate: 28.94 },
    { state: 'DC', rate: 36.39 },
    { state: 'DE', rate: 30.49 },
    { state: 'FL', rate: 29.95 },
    { state: 'GA', rate: 26.51 },
    { state: 'HI', rate: 34.83 },
    { state: 'IA', rate: 37.02 },
    { state: 'ID', rate: 36.22 },
    { state: 'IL', rate: 32.63 },
    { state: 'IN', rate: 30.7 },
    { state: 'KS', rate: 37.07 },
    { state: 'KY', rate: 26.75 },
    { state: 'LA', rate: 33.79 },
    { state: 'MA', rate: 40.05 },
    { state: 'MD', rate: 31.04 },
    { state: 'ME', rate: 33.07 },
    { state: 'MI', rate: 31.67 },
    { state: 'MN', rate: 34.96 },
    { state: 'MO', rate: 33.5 },
    { state: 'MS', rate: 25.75 },
    { state: 'MT', rate: 37.98 },
    { state: 'NC', rate: 27.05 },
    { state: 'ND', rate: 43.22 },
    { state: 'NE', rate: 38.49 },
    { state: 'NH', rate: 48.53 },
    { state: 'NJ', rate: 39.79 },
    { state: 'NM', rate: 38.47 },
    { state: 'NV', rate: 37.18 },
    { state: 'NY', rate: 37.27 },
    { state: 'OH', rate: 34.31 },
    { state: 'OK', rate: 30.22 },
    { state: 'OR', rate: 36.48 },
    { state: 'PA', rate: 31.1 },
    { state: 'PR', rate: 41.19 },
    { state: 'RI', rate: 31.35 },
    { state: 'SC', rate: 28.6 },
    { state: 'SD', rate: 42.14 },
    { state: 'TN', rate: 26.47 },
    { state: 'TX', rate: 33.32 },
    { state: 'UT', rate: 36.76 },
    { state: 'VA', rate: 37.28 },
    { state: 'VT', rate: 42.48 },
    { state: 'WA', rate: 38.12 },
    { state: 'WI', rate: 38.29 },
    { state: 'WV', rate: 28.23 },
    { state: 'WY', rate: 58.03 },
  ],
  2015: [
    { state: 'AK', rate: 50.68 },
    { state: 'AL', rate: 26.93 },
    { state: 'AR', rate: 31.1 },
    { state: 'AZ', rate: 27.08 },
    { state: 'CA', rate: 33.69 },
    { state: 'CO', rate: 31.29 },
    { state: 'CT', rate: 31.07 },
    { state: 'DC', rate: 34.25 },
    { state: 'DE', rate: 35.35 },
    { state: 'FL', rate: 30.53 },
    { state: 'GA', rate: 28.37 },
    { state: 'HI', rate: 33.34 },
    { state: 'IA', rate: 38.61 },
    { state: 'ID', rate: 37.3 },
    { state: 'IL', rate: 33.8 },
    { state: 'IN', rate: 31.05 },
    { state: 'KS', rate: 38.47 },
    { state: 'KY', rate: 29.64 },
    { state: 'LA', rate: 37.51 },
    { state: 'MA', rate: 40.63 },
    { state: 'MD', rate: 33.28 },
    { state: 'ME', rate: 35.86 },
    { state: 'MI', rate: 32.72 },
    { state: 'MN', rate: 34.57 },
    { state: 'MO', rate: 35.1 },
    { state: 'MS', rate: 25.79 },
    { state: 'MT', rate: 36.33 },
    { state: 'NC', rate: 26.54 },
    { state: 'ND', rate: 41.46 },
    { state: 'NE', rate: 40.61 },
    { state: 'NH', rate: 48.05 },
    { state: 'NJ', rate: 38.86 },
    { state: 'NM', rate: 42.28 },
    { state: 'NV', rate: 40.12 },
    { state: 'NY', rate: 36.69 },
    { state: 'OH', rate: 33.67 },
    { state: 'OK', rate: 32.62 },
    { state: 'OR', rate: 35.17 },
    { state: 'PA', rate: 30.83 },
    { state: 'PR', rate: 43.02 },
    { state: 'RI', rate: 32.9 },
    { state: 'SC', rate: 29.33 },
    { state: 'SD', rate: 39.46 },
    { state: 'TN', rate: 27.23 },
    { state: 'TX', rate: 34.09 },
    { state: 'UT', rate: 36.68 },
    { state: 'VA', rate: 38.03 },
    { state: 'VT', rate: 43.35 },
    { state: 'WA', rate: 37.85 },
    { state: 'WI', rate: 36 },
    { state: 'WV', rate: 28.74 },
    { state: 'WY', rate: 48.74 },
  ],
  2016: [
    { state: 'AK', rate: 52.14 },
    { state: 'AL', rate: 26.67 },
    { state: 'AR', rate: 31.52 },
    { state: 'AZ', rate: 26.26 },
    { state: 'CA', rate: 32.9 },
    { state: 'CO', rate: 33.27 },
    { state: 'CT', rate: 31.38 },
    { state: 'DC', rate: 35.44 },
    { state: 'DE', rate: 36.47 },
    { state: 'FL', rate: 31.39 },
    { state: 'GA', rate: 30.69 },
    { state: 'HI', rate: 31.9 },
    { state: 'IA', rate: 38.11 },
    { state: 'ID', rate: 39.43 },
    { state: 'IL', rate: 32.85 },
    { state: 'IN', rate: 30.84 },
    { state: 'KS', rate: 41.91 },
    { state: 'KY', rate: 30.03 },
    { state: 'LA', rate: 37.67 },
    { state: 'MA', rate: 41.17 },
    { state: 'MD', rate: 33.16 },
    { state: 'ME', rate: 34.29 },
    { state: 'MI', rate: 33.71 },
    { state: 'MN', rate: 34.7 },
    { state: 'MO', rate: 32.64 },
    { state: 'MS', rate: 25.67 },
    { state: 'MT', rate: 37.49 },
    { state: 'NC', rate: 25.75 },
    { state: 'ND', rate: 44.8 },
    { state: 'NE', rate: 39.42 },
    { state: 'NH', rate: 51.43 },
    { state: 'NJ', rate: 37.87 },
    { state: 'NM', rate: 35.03 },
    { state: 'NV', rate: 37.72 },
    { state: 'NY', rate: 36.98 },
    { state: 'OH', rate: 34.06 },
    { state: 'OK', rate: 30.27 },
    { state: 'OR', rate: 37.03 },
    { state: 'PA', rate: 35 },
    { state: 'PR', rate: 43.12 },
    { state: 'RI', rate: 36.21 },
    { state: 'SC', rate: 30.76 },
    { state: 'SD', rate: 38.93 },
    { state: 'TN', rate: 27.74 },
    { state: 'TX', rate: 33.97 },
    { state: 'UT', rate: 36.36 },
    { state: 'VA', rate: 38.87 },
    { state: 'VT', rate: 42.39 },
    { state: 'WA', rate: 38.5 },
    { state: 'WI', rate: 34.76 },
    { state: 'WV', rate: 27.46 },
    { state: 'WY', rate: 48.39 },
  ],
  2017: [
    { state: 'AK', rate: 45.21 },
    { state: 'AL', rate: 27.36 },
    { state: 'AR', rate: 33.25 },
    { state: 'AZ', rate: 27.29 },
    { state: 'CA', rate: 33.83 },
    { state: 'CO', rate: 35.2 },
    { state: 'CT', rate: 34.13 },
    { state: 'DC', rate: 36.98 },
    { state: 'DE', rate: 36.53 },
    { state: 'FL', rate: 32.92 },
    { state: 'GA', rate: 31.71 },
    { state: 'HI', rate: 36.15 },
    { state: 'IA', rate: 38.09 },
    { state: 'ID', rate: 41.18 },
    { state: 'IL', rate: 36.12 },
    { state: 'IN', rate: 29.94 },
    { state: 'KS', rate: 46.03 },
    { state: 'KY', rate: 30.54 },
    { state: 'LA', rate: 38.27 },
    { state: 'MA', rate: 41.26 },
    { state: 'MD', rate: 33.04 },
    { state: 'ME', rate: 35.92 },
    { state: 'MI', rate: 36.38 },
    { state: 'MN', rate: 35.58 },
    { state: 'MO', rate: 34.94 },
    { state: 'MS', rate: 25.29 },
    { state: 'MT', rate: 36.29 },
    { state: 'NC', rate: 26.41 },
    { state: 'ND', rate: 45.29 },
    { state: 'NE', rate: 42.22 },
    { state: 'NH', rate: 50.92 },
    { state: 'NJ', rate: 38.74 },
    { state: 'NM', rate: 33.98 },
    { state: 'NV', rate: 33.18 },
    { state: 'NY', rate: 38.18 },
    { state: 'OH', rate: 35.36 },
    { state: 'OK', rate: 29.24 },
    { state: 'OR', rate: 36.2 },
    { state: 'PA', rate: 36.49 },
    { state: 'RI', rate: 36.62 },
    { state: 'SC', rate: 32.03 },
    { state: 'SD', rate: 39.23 },
    { state: 'TN', rate: 28.7 },
    { state: 'TX', rate: 34.68 },
    { state: 'UT', rate: 37.14 },
    { state: 'VA', rate: 40.6 },
    { state: 'VT', rate: 45.76 },
    { state: 'WA', rate: 39.43 },
    { state: 'WI', rate: 36.71 },
    { state: 'WV', rate: 29.05 },
    { state: 'WY', rate: 49.19 },
  ],
  2018: [
    { state: 'AK', rate: 46.22 },
    { state: 'AL', rate: 31 },
    { state: 'AR', rate: 32.9 },
    { state: 'AZ', rate: 28.02 },
    { state: 'CA', rate: 34.37 },
    { state: 'CO', rate: 39.62 },
    { state: 'CT', rate: 34.6 },
    { state: 'DC', rate: 37.91 },
    { state: 'DE', rate: 39.7 },
    { state: 'FL', rate: 34.31 },
    { state: 'GA', rate: 33.41 },
    { state: 'HI', rate: 34.69 },
    { state: 'IA', rate: 38.09 },
    { state: 'ID', rate: 40.38 },
    { state: 'IL', rate: 36.28 },
    { state: 'IN', rate: 30.11 },
    { state: 'KS', rate: 47.36 },
    { state: 'KY', rate: 29.41 },
    { state: 'LA', rate: 41.61 },
    { state: 'MA', rate: 41.07 },
    { state: 'MD', rate: 32.85 },
    { state: 'ME', rate: 34.43 },
    { state: 'MI', rate: 38.14 },
    { state: 'MN', rate: 38.34 },
    { state: 'MO', rate: 36.12 },
    { state: 'MS', rate: 25.29 },
    { state: 'MT', rate: 37.22 },
    { state: 'NC', rate: 29.24 },
    { state: 'ND', rate: 45.37 },
    { state: 'NE', rate: 40.99 },
    { state: 'NH', rate: 51.51 },
    { state: 'NJ', rate: 38.32 },
    { state: 'NM', rate: 33.31 },
    { state: 'NV', rate: 33.59 },
    { state: 'NY', rate: 39.08 },
    { state: 'OH', rate: 36.18 },
    { state: 'OK', rate: 29.32 },
    { state: 'OR', rate: 39.48 },
    { state: 'PA', rate: 38.95 },
    { state: 'PR', rate: 48.76 },
    { state: 'RI', rate: 37.6 },
    { state: 'SC', rate: 32.8 },
    { state: 'SD', rate: 36.45 },
    { state: 'TN', rate: 28.94 },
    { state: 'TX', rate: 33.39 },
    { state: 'UT', rate: 37.95 },
    { state: 'VA', rate: 42.1 },
    { state: 'VT', rate: 44.38 },
    { state: 'WA', rate: 38 },
    { state: 'WI', rate: 36.8 },
    { state: 'WV', rate: 29.87 },
    { state: 'WY', rate: 51.96 },
  ],
  2019: [
    { state: 'AK', rate: 47.71 },
    { state: 'AL', rate: 33.42 },
    { state: 'AR', rate: 34.65 },
    { state: 'AZ', rate: 30.99 },
    { state: 'CA', rate: 36.62 },
    { state: 'CO', rate: 43.13 },
    { state: 'CT', rate: 36.57 },
    { state: 'DC', rate: 35.93 },
    { state: 'DE', rate: 37.7 },
    { state: 'FL', rate: 36 },
    { state: 'GA', rate: 36.15 },
    { state: 'HI', rate: 35.52 },
    { state: 'IA', rate: 42.34 },
    { state: 'ID', rate: 44.67 },
    { state: 'IL', rate: 37.66 },
    { state: 'IN', rate: 31.83 },
    { state: 'KS', rate: 53.05 },
    { state: 'KY', rate: 31.99 },
    { state: 'LA', rate: 42.51 },
    { state: 'MA', rate: 42.88 },
    { state: 'MD', rate: 35.42 },
    { state: 'ME', rate: 39.57 },
    { state: 'MI', rate: 40.8 },
    { state: 'MN', rate: 40.54 },
    { state: 'MO', rate: 40.03 },
    { state: 'MS', rate: 28.21 },
    { state: 'MT', rate: 41.58 },
    { state: 'NC', rate: 33.84 },
    { state: 'ND', rate: 49.85 },
    { state: 'NE', rate: 47.33 },
    { state: 'NH', rate: 52.66 },
    { state: 'NJ', rate: 40.4 },
    { state: 'NM', rate: 35.74 },
    { state: 'NV', rate: 33.84 },
    { state: 'NY', rate: 40.56 },
    { state: 'OH', rate: 37.58 },
    { state: 'OK', rate: 30.39 },
    { state: 'OR', rate: 40.63 },
    { state: 'PA', rate: 40.71 },
    { state: 'PR', rate: 45.6 },
    { state: 'RI', rate: 42.66 },
    { state: 'SC', rate: 35.14 },
    { state: 'SD', rate: 41.61 },
    { state: 'TN', rate: 33.41 },
    { state: 'TX', rate: 34.73 },
    { state: 'UT', rate: 43.95 },
    { state: 'VA', rate: 43.77 },
    { state: 'VT', rate: 46.18 },
    { state: 'WA', rate: 38.79 },
    { state: 'WI', rate: 39.94 },
    { state: 'WV', rate: 31.92 },
    { state: 'WY', rate: 56.06 },
  ],
  2020: [
    { state: 'AK', rate: 55.52 },
    { state: 'AL', rate: 33.09 },
    { state: 'AR', rate: 35.51 },
    { state: 'AZ', rate: 34.67 },
    { state: 'CA', rate: 39.69 },
    { state: 'CO', rate: 40.9 },
    { state: 'CT', rate: 40.01 },
    { state: 'DC', rate: 35.03 },
    { state: 'DE', rate: 39.63 },
    { state: 'FL', rate: 37.12 },
    { state: 'GA', rate: 40.63 },
    { state: 'HI', rate: 37.4 },
    { state: 'IA', rate: 45.92 },
    { state: 'ID', rate: 46.49 },
    { state: 'IL', rate: 41.01 },
    { state: 'IN', rate: 33.48 },
    { state: 'KS', rate: 62.84 },
    { state: 'KY', rate: 33.98 },
    { state: 'LA', rate: 39.77 },
    { state: 'MA', rate: 45.82 },
    { state: 'MD', rate: 39.06 },
    { state: 'ME', rate: 36.6 },
    { state: 'MI', rate: 41.32 },
    { state: 'MN', rate: 45.58 },
    { state: 'MO', rate: 41.31 },
    { state: 'MS', rate: 29.96 },
    { state: 'MT', rate: 45.03 },
    { state: 'NC', rate: 34.84 },
    { state: 'ND', rate: 49.8 },
    { state: 'NE', rate: 51.24 },
    { state: 'NH', rate: 59.09 },
    { state: 'NJ', rate: 43.22 },
    { state: 'NM', rate: 37.02 },
    { state: 'NV', rate: 37.56 },
    { state: 'NY', rate: 45.47 },
    { state: 'OH', rate: 40.08 },
    { state: 'OK', rate: 30.4 },
    { state: 'OR', rate: 41.85 },
    { state: 'PA', rate: 40.76 },
    { state: 'PR', rate: 47.12 },
    { state: 'RI', rate: 45.25 },
    { state: 'SC', rate: 38.27 },
    { state: 'SD', rate: 47.62 },
    { state: 'TN', rate: 38.84 },
    { state: 'TX', rate: 35.94 },
    { state: 'UT', rate: 48.77 },
    { state: 'VA', rate: 43.35 },
    { state: 'VT', rate: 46.41 },
    { state: 'WA', rate: 42.12 },
    { state: 'WI', rate: 40.7 },
    { state: 'WV', rate: 34.39 },
    { state: 'WY', rate: 54.4 },
  ],
  2021: [
    { state: 'AK', rate: 56.53 },
    { state: 'AL', rate: 32.87 },
    { state: 'AR', rate: 36.06 },
    { state: 'AZ', rate: 31.43 },
    { state: 'CA', rate: 36.51 },
    { state: 'CO', rate: 34.85 },
    { state: 'CT', rate: 40.31 },
    { state: 'DC', rate: 26.88 },
    { state: 'DE', rate: 37.59 },
    { state: 'FL', rate: 33.85 },
    { state: 'GA', rate: 38.03 },
    { state: 'HI', rate: 35.16 },
    { state: 'IA', rate: 42.13 },
    { state: 'ID', rate: 42.99 },
    { state: 'IL', rate: 36.97 },
    { state: 'IN', rate: 31.37 },
    { state: 'KS', rate: 60.57 },
    { state: 'KY', rate: 31.63 },
    { state: 'LA', rate: 39.8 },
    { state: 'MA', rate: 42.95 },
    { state: 'MD', rate: 38.9 },
    { state: 'ME', rate: 35.01 },
    { state: 'MI', rate: 39.35 },
    { state: 'MN', rate: 42.15 },
    { state: 'MO', rate: 38.27 },
    { state: 'MS', rate: 30.64 },
    { state: 'MT', rate: 41.62 },
    { state: 'NC', rate: 33.07 },
    { state: 'ND', rate: 45.52 },
    { state: 'NE', rate: 47.21 },
    { state: 'NH', rate: 50.57 },
    { state: 'NJ', rate: 39.59 },
    { state: 'NM', rate: 35.29 },
    { state: 'NV', rate: 38.04 },
    { state: 'NY', rate: 37.53 },
    { state: 'OH', rate: 36.87 },
    { state: 'OK', rate: 29.14 },
    { state: 'OR', rate: 41.85 },
    { state: 'PA', rate: 38.53 },
    { state: 'PR', rate: 42.15 },
    { state: 'RI', rate: 46.14 },
    { state: 'SC', rate: 35.94 },
    { state: 'SD', rate: 40.76 },
    { state: 'TN', rate: 35.09 },
    { state: 'TX', rate: 33.71 },
    { state: 'UT', rate: 37.64 },
    { state: 'VA', rate: 44.12 },
    { state: 'VT', rate: 43.8 },
    { state: 'WA', rate: 39.51 },
    { state: 'WI', rate: 37.91 },
    { state: 'WV', rate: 30.71 },
    { state: 'WY', rate: 44.22 },
  ],
};

const ssaYears = Object.keys(ssaApprovalByYear)
  .map(year => Number(year))
  .sort((a, b) => a - b);

const ssaApprovalTrend = [
  { name: '2001', value: 41.02 },
  { name: '2002', value: 39.18 },
  { name: '2003', value: 37.39 },
  { name: '2004', value: 37.52 },
  { name: '2005', value: 36.98 },
  { name: '2006', value: 37.03 },
  { name: '2007', value: 36.4 },
  { name: '2008', value: 37.8 },
  { name: '2009', value: 38.77 },
  { name: '2010', value: 37.35 },
  { name: '2011', value: 35.7 },
  { name: '2012', value: 35.25 },
  { name: '2013', value: 35.31 },
  { name: '2014', value: 34.85 },
  { name: '2015', value: 35.32 },
  { name: '2016', value: 35.51 },
  { name: '2017', value: 36.17 },
  { name: '2018', value: 37.07 },
  { name: '2019', value: 39.51 },
  { name: '2020', value: 41.77 },
  { name: '2021', value: 38.83 },
];

export function ProjectCharts({ slug }: ProjectChartsProps) {
  const [selectedYear, setSelectedYear] = useState<number>(ssaYears[ssaYears.length - 1]);
  const mapData = useMemo(
    () => ssaApprovalByYear[selectedYear] ?? [],
    [selectedYear]
  );
  const mapLocations = mapData.map(entry => entry.state);
  const mapValues = mapData.map(entry => entry.rate);

  if (slug === 'customer-segmentation-dashboard') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Interactive Segment Insights</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <Chart
            type="pie"
            title="Customer Segment Distribution (%)"
            data={[
              { name: 'High-Value Loyalists', value: 8 },
              { name: 'Occasional Bargain Hunters', value: 22 },
              { name: 'New Explorers', value: 15 },
              { name: 'Brand Devotees', value: 12 },
              { name: 'Multi-Channel Shoppers', value: 18 },
              { name: 'At-Risk Customers', value: 8 },
            ]}
            height={320}
          />
          <Chart
            type="bar"
            title="Campaign Conversion Rate (%)"
            data={[
              { name: 'Before Segmentation', value: 3.2 },
              { name: 'After Segmentation', value: 4.5 },
            ]}
            height={280}
          />
        </CardContent>
      </Card>
    );
  }

  if (slug === 'ecommerce-recommendation-engine') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Recommendation Impact</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <Chart
            type="bar"
            title="Click-Through Rate Improvement (%)"
            data={[
              { name: 'Before System', value: 4.2 },
              { name: 'After System', value: 5.8 },
            ]}
            height={260}
          />
          <div className="h-[320px]">
            <PlotlyChart
              data={[
                {
                  type: 'scatter',
                  mode: 'lines+markers',
                  x: ['Month 1', 'Month 2', 'Month 3', 'Month 4', 'Month 5', 'Month 6'],
                  y: [100, 250, 450, 680, 920, 1200],
                  line: { color: '#2563eb', width: 3 },
                },
              ]}
              layout={{
                title: 'Monthly Revenue Impact ($K)',
                xaxis: { title: 'Month' },
                yaxis: { title: 'Revenue ($K)' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
              }}
              className="h-full w-full"
            />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (slug === 'babynames-ssa-visual-story') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Interactive Baby Names Trends</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <Chart
            type="line"
            title="Total Births by Year (2015–2024)"
            data={babynamesBirthsRecent}
            height={300}
            color="#a0cbe8"
          />
          <Chart
            type="bar"
            title="Top 10 Names Overall (1880–2024)"
            data={babynamesTopNames}
            height={340}
            color="#e14f7a"
          />
          <Chart
            type="line"
            title="Unique Names per Year (2015–2024)"
            data={babynamesUniqueNamesRecent}
            height={280}
            color="#f59e0b"
          />
          <div className="h-[360px]">
            <PlotlyChart
              data={[
                {
                  type: 'bar',
                  name: 'Female',
                  x: babynamesUnisexNames.names,
                  y: babynamesUnisexNames.female,
                  marker: { color: '#e14f7a' },
                },
                {
                  type: 'bar',
                  name: 'Male',
                  x: babynamesUnisexNames.names,
                  y: babynamesUnisexNames.male,
                  marker: { color: '#a0cbe8' },
                },
              ]}
              layout={{
                title: 'Top Unisex Names (Female vs Male Counts)',
                barmode: 'group',
                xaxis: { title: 'Name' },
                yaxis: { title: 'Total Count' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
              }}
              className="h-full w-full"
            />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (slug === 'f5-breach-threat-intelligence') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Breach Impact Signals</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="h-[320px]">
            <PlotlyChart
              data={[
                {
                  type: 'scatter',
                  mode: 'lines+markers',
                  x: f5BreachReturns.dates,
                  y: f5BreachReturns.returns,
                  line: { color: '#1d4ed8', width: 3 },
                  name: 'FFIV Daily Returns',
                },
              ]}
              layout={{
                title: 'FFIV Returns Around Breach Date',
                xaxis: { title: 'Date' },
                yaxis: { title: 'Daily Return' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
                shapes: [
                  {
                    type: 'line',
                    x0: '2025-10-16',
                    x1: '2025-10-16',
                    y0: Math.min(...f5BreachReturns.returns),
                    y1: Math.max(...f5BreachReturns.returns),
                    line: { color: '#ef4444', width: 2, dash: 'dash' },
                  },
                ],
              }}
              className="h-full w-full"
            />
          </div>
          <div className="h-[320px]">
            <PlotlyChart
              data={[
                {
                  type: 'scatter',
                  mode: 'lines+markers',
                  x: f5BreachReturns.dates,
                  y: f5BreachCumulativeIndex,
                  line: { color: '#0f172a', width: 3 },
                  fill: 'tozeroy',
                  fillcolor: 'rgba(148, 163, 184, 0.2)',
                  name: 'Cumulative Return Index',
                },
              ]}
              layout={{
                title: 'Stock Impact Index (Cumulative Return)',
                xaxis: { title: 'Date' },
                yaxis: { title: 'Index (Base = 100)' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
                shapes: [
                  {
                    type: 'line',
                    x0: '2025-10-16',
                    x1: '2025-10-16',
                    y0: Math.min(...f5BreachCumulativeIndex),
                    y1: Math.max(...f5BreachCumulativeIndex),
                    line: { color: '#ef4444', width: 2, dash: 'dash' },
                  },
                ],
              }}
              className="h-full w-full"
            />
          </div>
          <Chart
            type="bar"
            title="Difference-in-Differences Coefficients"
            data={f5BreachDiD}
            height={260}
            color="#ef4444"
          />
          <Chart
            type="bar"
            title="Core DiD Model Coefficients"
            data={f5BreachCoefficients}
            height={280}
            color="#0f172a"
          />
        </CardContent>
      </Card>
    );
  }

  if (slug === 'ssa-disability-outcomes') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>SSA Approval Rate Patterns (FY{selectedYear})</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="rounded-lg border p-4 space-y-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="text-sm font-medium">Fiscal Year</div>
              <div className="text-sm text-muted-foreground">{selectedYear}</div>
            </div>
            <input
              type="range"
              min={ssaYears[0]}
              max={ssaYears[ssaYears.length - 1]}
              step={1}
              value={selectedYear}
              onChange={event => setSelectedYear(Number(event.target.value))}
              className="w-full accent-primary"
              aria-label="Select fiscal year"
            />
            <div className="flex items-center justify-between text-xs text-muted-foreground">
              <span>{ssaYears[0]}</span>
              <span>{ssaYears[ssaYears.length - 1]}</span>
            </div>
          </div>
          <div className="h-[420px]">
            <PlotlyChart
              data={[
                {
                  type: 'choropleth',
                  locationmode: 'USA-states',
                  locations: mapLocations,
                  z: mapValues,
                  colorscale: [
                    [0, '#e0f2fe'],
                    [0.5, '#60a5fa'],
                    [1, '#1d4ed8'],
                  ],
                  marker: {
                    line: { color: '#ffffff', width: 1 },
                  },
                  colorbar: { title: 'Approval %' },
                  hovertemplate: '%{location}: %{z:.2f}%<extra></extra>',
                },
              ]}
              layout={{
                title: `Favorable Determination Rate by State (FY${selectedYear})`,
                geo: { scope: 'usa', projection: { type: 'albers usa' } },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
                margin: { l: 0, r: 0, t: 50, b: 0 },
              }}
              className="h-full w-full"
            />
          </div>
          <div className="h-[320px]">
            <PlotlyChart
              data={[
                {
                  type: 'scatter',
                  mode: 'lines+markers',
                  x: ssaApprovalTrend.map(entry => entry.name),
                  y: ssaApprovalTrend.map(entry => entry.value),
                  line: { color: '#1d4ed8', width: 3 },
                  name: 'Average Approval Rate',
                },
              ]}
              layout={{
                title: 'Average Approval Rate Trend (FY2001–FY2021)',
                xaxis: { title: 'Fiscal Year' },
                yaxis: { title: 'Approval Rate (%)' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
                shapes: [
                  {
                    type: 'line',
                    x0: '2020',
                    x1: '2020',
                    y0: Math.min(...ssaApprovalTrend.map(entry => entry.value)),
                    y1: Math.max(...ssaApprovalTrend.map(entry => entry.value)),
                    line: { color: '#ef4444', width: 2, dash: 'dash' },
                  },
                ],
                annotations: [
                  {
                    x: '2020',
                    y: Math.max(...ssaApprovalTrend.map(entry => entry.value)),
                    text: 'COVID onset',
                    showarrow: false,
                    yanchor: 'bottom',
                    font: { color: '#ef4444' },
                  },
                ],
              }}
              className="h-full w-full"
            />
          </div>
          <Chart
            type="bar"
            title="Top States by Favorable Determination Rate"
            data={ssaApprovalTopStates}
            height={320}
            color="#2563eb"
          />
          <Chart
            type="bar"
            title="Lowest States by Favorable Determination Rate"
            data={ssaApprovalBottomStates}
            height={320}
            color="#94a3b8"
          />
          <div className="h-[340px]">
            <PlotlyChart
              data={[
                {
                  type: 'bar',
                  name: 'Adult Approval Rate',
                  x: ssaAdultChildRates.states,
                  y: ssaAdultChildRates.adult,
                  marker: { color: '#2563eb' },
                },
                {
                  type: 'bar',
                  name: 'Child Approval Rate',
                  x: ssaAdultChildRates.states,
                  y: ssaAdultChildRates.child,
                  marker: { color: '#22c55e' },
                },
              ]}
              layout={{
                title: 'Adult vs Child Approval Rates (Top States)',
                barmode: 'group',
                xaxis: { title: 'State' },
                yaxis: { title: 'Approval Rate (%)' },
                paper_bgcolor: 'transparent',
                plot_bgcolor: 'transparent',
              }}
              className="h-full w-full"
            />
          </div>
        </CardContent>
      </Card>
    );
  }

  return null;
}
